# Generated by Django 6.0.6 on 2026-06-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=100)),
                ('age_bracket', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('determination_score', models.IntegerField(default=0)),
                ('mastery_score', models.IntegerField(default=0)),
                ('player_level', models.IntegerField(default=0)),
                ('session_duration_seconds', models.IntegerField(default=0)),
                ('total_questions_answered', models.IntegerField(default=0)),
                ('session_accuracy_percent', models.IntegerField(default=0)),
                ('levels_gained', models.IntegerField(default=0)),
                ('mastery_gained', models.IntegerField(default=0)),
                ('determination_gained', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MathProgress',
        ),
    ]
