# Generated by Django 6.0.6 on 2026-06-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0002_leaderboardentry_delete_mathprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=5, null=True)),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('avg_mastery', models.IntegerField(default=0)),
                ('avg_determination', models.IntegerField(default=0)),
                ('highest_level', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('country', 'state')},
            },
        ),
    ]
