# Generated by Django 6.0.6 on 2026-06-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("math_app", "0003_analyticssummary"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="analyticssummary",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="analyticssummary",
            name="module_type",
            field=models.CharField(default="multiplication", max_length=50),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="module_type",
            field=models.CharField(default="multiplication", max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="analyticssummary",
            unique_together={("country", "state", "module_type")},
        ),
    ]
